spring:
  profiles:
    active: local

  mail:
    host: smtp.qq.com
    port: 465
    username: 531237716@qq.com
    password: ENC(pS7NvCDk4ouixF9t8kcIPfrRUr/ZZ3J+JGBYc5yT4TAGHb8YBLu7r3l2ZSWoPuFIy7ROpcPHZCP/gYBTHWpNvw==)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    enable-spring-el-compiler: true

  cache:
    type: redis

#  redis:
#    #集群模式
#    cluster:
#      nodes: 192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
#      max-redirects: 3
#    #哨兵模式
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26479

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
#        wall:
#          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: true
        session-stat-max-count: 100000
      aop-patterns: 'com.cn.*'
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: true
#        login-username: 123456
#        login-password: admin


oss:
  config:
    host: https://oss-cn-hongkong-internal.aliyuncs.com
    bucket-name: music-story
    access-key-id: ENC(BFmGqMfhERt8BVG81BuQFAI4L165TxyjahwvlTGx9QnjkKAWytNvhhtfiajw1mhsGTLh5JErMOFrjltogIkOUg==)
    access-key-secret: ENC(Ng+yTJPV6RPseJCbuVbk2vqwElnl5fdddl22TAYCvyOVoHSjINi9Tk01j+8CLmozS/ysp3gWFbU5Ock4znKENw==)
    endpoint: oss.ngcly.cn
