// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/7/16 19:16:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/git项目/MusicStory/apps/web-client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git项目/MusicStory/apps/web-client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git项目/MusicStory/apps/web-client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git项目/MusicStory/apps/web-client/plugins/**/*.{js,ts,mjs}","D:/git项目/MusicStory/apps/web-client/composables/**/*.{js,ts,mjs}","D:/git项目/MusicStory/apps/web-client/utils/**/*.{js,ts,mjs}","D:/git项目/MusicStory/apps/web-client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/git项目/MusicStory/apps/web-client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/git项目/MusicStory/apps/web-client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/git项目/MusicStory/apps/web-client/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;