spring:
  profiles:
    active: local
  threads:
    virtual:
      enabled: true

  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    enable-spring-el-compiler: true

  cache:
    type: redis

#  redis:
#    #集群模式
#    cluster:
#      nodes: 192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
#      max-redirects: 3
#    #哨兵模式
#    sentinel:
#      master: mymaster
#      nodes: 127.0.0.1:26379,127.0.0.1:26479



oss:
  config:
    host: ${OSS_HOST:https://oss-cn-hongkong-internal.aliyuncs.com}
    bucket-name: ${OSS_BUCKET_NAME:music-story}
    access-key-id: ${OSS_ACCESS_KEY_ID:dev-only-access-key-id}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:dev-only-access-key-secret}
    endpoint: ${OSS_ENDPOINT:oss.ngcly.cn}
